services:
    osm_easy_rest.listener.request_content_listener:
        class: Osm\EasyRestBundle\EventListener\RequestContentListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    osm_easy_rest.listener.json_response_listener :
        class: Osm\EasyRestBundle\EventListener\JsonResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
